# Generated by Django 5.2.1 on 2025-06-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=200)),
                ('applicant', models.CharField(max_length=200)),
                ('company_branch', models.CharField(max_length=200)),
            ],
        ),
    ]
