# Generated by Django 5.2.1 on 2025-06-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='branch',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='company_branch',
            new_name='company_brand',
        ),
    ]
